name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.10.0"
          rebar3-version: "3"
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: gleam test
      - run: gleam test --target javascript
      - run: gleam format --check src test
